# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# test

trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - products/storage/*
    exclude:
    - products/**
    - pipelines/**

pr: 
  autoCancel: false
  branches:
    include:
      - 'main'
  paths:
    include:
      - products/storage/*
      - products/storage/*
    exclude:
      - products/**
      - pipelines/**
  drafts: true    

pool:
  vmImage: ubuntu-latest

stages:
- stage: 'Build'
  displayName: 'Build the web application'
  jobs: 
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: 'ubuntu-20.04'
      demands:
      - npm

    variables:
      wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
      dotnetSdkVersion: '6.x'

    steps:
      - script: echo Hello, world!
        displayName: 'Run a one-line script'

      - script: |
          echo Add other tasks to build, test, and deploy your project.
          echo See https://aka.ms/yaml
        displayName: 'Run a multi-line script'

# - stage: 'Deploy'
#   displayName: 'Build the web application'
#   jobs: 
#   - job: 'Deploy'
#     displayName: 'Build job'
#     pool:
#       vmImage: 'ubuntu-20.04'
#       demands:
#       - npm
#     steps:
#       - script: echo Hello, world!
#         displayName: 'Run a one-line script'

#       - script: |
#           echo Add other tasks to build, test, and deploy your project.
#           echo See https://aka.ms/yaml
#         displayName: 'Run a multi-line script'